# action.yml
name: 'aziona'

description: 'Action aziona-cli docker'

inputs:
  target:
    description: 'Target'
    required: true
  aziona_cli_version:
    description: 'Aziona cli version'
    default: ""

outputs:
  result:
    description: 'Build result'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}