# action.yml
name: 'aziona'

description: 'Action aziona-cli docker'

inputs:
  file:
    description: 'File aziona'
    default: .aziona.yml
    required: false
  target:
    description: 'Target'
    required: true
  verbosity:
    description: 'Verbosity level (1, 2 or 3)'
    default: "1"
    required: true

outputs:
  result:
    description: 'Build result'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --verbosity${{ inputs.verbosity }}
    - -f${{ inputs.file }}
    - targets${{ inputs.target }}
