# action.yml
name: 'aziona'

description: 'Action aziona-cli docker'

inputs:
  target:
    description: 'Target'
    required: true
  aziona_cli_version:
    description: 'Aziona cli version (install from pypi.org)'
    default: ""
  aziona_cli_buildfile:
    description: 'Aziona cli build file local'
    default: "false"

outputs:
  result:
    description: 'Build result'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AZIONA_CLI_BUILDFILE: ${{ inputs.aziona_cli_buildfile }}
    AZIONA_CLI_VERSION: ${{ inputs.aziona_cli_version }}
  args:
    - ${{ inputs.target }}