# action.yml
name: 'aziona'

description: 'Action aziona-cli docker'

inputs:
  file:
    description: 'File aziona'
    default: .aziona.yml
    required: false
  target:
    description: 'Target'
    required: true

outputs:
  result:
    description: 'Build result'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f ${{ inputs.file }}
    - ${{ inputs.target }}