
name: Create release tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
  
jobs:
  create-new-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create
        run: |
          chmod +x -R scripts/ci
          ./scripts/ci/create-release.sh --version ${{ github.event.inputs.version }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: FabrizioCafolla
          author_email: developer@fabriziocafolla.com
          message: 'Create version: ${{ github.event.inputs.version }}. Commit: ${{ github.sha }}'
          add: 'aziona/__init__.py'
          tag: 'v${{ github.event.inputs.version }} --force'