
name: Release image docker

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch name ref
        default:  "main"
  
jobs:
  release-docker:
    runs-on: ubuntu-20.04
    environment: Release
    needs: release-package
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            azionaventures/aziona-cli
          tags: |
            type=ref,event=branch
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AZIONA_CLI_BUILDFILE=true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}