
name: Release py package and publish docs

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      py_version:
        description: PY version
        default:  3.9
  
jobs:
  release-package:
    runs-on: ubuntu-20.04
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build
        run: |
          make build-wheel
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          skip_existing: true
  release-docker:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    environment: Release
    needs: release-package
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            azionaventures/aziona-cli
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  release-docs:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    needs: ['release-package', 'release-docker']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build docs
        run: |
          make build-docs
      - name: Publish docs on github pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
  catch-error:
    if:  ${{ startsWith(github.ref, 'refs/tags') && failure() }}
    runs-on: ubuntu-20.04
    environment: Release
    needs: release-docs
    steps:
      - name: Get the version
        id: version
        run: echo ::set-output name=AZIONA_CLI_VERSION::$(echo $GITHUB_REF | cut -d v -f 2)
      - name: Delete release tag 
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v${{ steps.version.outputs.AZIONA_CLI_VERSION }}
          repo: azionaventures/aziona-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  